### ISSUE TITLE
Ubuntu-based image is broken

### ISSUE THREAD

**Issue by awasilyev** [tarantool/tarantool-docker#3]
[root@js ~]# docker run -d --name tarantool1 tarantool/tarantool
docker: Error response from daemon: mkdir /var/lib/docker/overlay/0d397c1833aa41c415577727e34727f1be7992c6ef8df654aab408de7562955a-init/merged/dev/shm: invalid argument.
See 'docker run --help'.

docker-1.11.2, overlayfs over xfs.

centos-based image is ok:
[root@js ~]# docker run -d --name tarantool2 tarantool/tarantool:centos
0f7f7e40937e30079eb5799747f93aac9f683f37d1c25bffc335b36f9bf1633d
[root@js ~]#

**Comment by racktear** [comment]
No longer applicable, since we moved to Alpine Linux
